---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: f3

enabled: false

stickinessProperty: rox.distinct_id

defaultValue: false

conditions:
  - anyOf:
      - property:
          name: cp3
          operator: is-true
    flagValue: true
